### ISSUE TITLE
Tournaments filter doesn't reflect what's selected when joining

### ISSUE THREAD

**Issue by Capronicus** [klesun/bcu-bugs-public#12]
figured I'd add this as well.
Basically when clicking join tournament it automatically already shows all cuties elligible, but the filter doesn't reflect that. Touching the filter in any form completely resets everything to how the filter is shown (by default all cuties)

Might throw in my request to change default tournament sorting to descending but I'm willing to put that up to a vote :)
[image](https://user-images.githubusercontent.com/39051437/137645858-2796d806-023e-4a07-b9e3-a0df0ae75983.png)![image](https://user-images.githubusercontent.com/39051437/137645858-2796d806-023e-4a07-b9e3-a0df0ae75983.png)

**Comment by klesun** [comment]
Internal ticket number: BC-3045
The fix was released in `21.11.5.1`
