### ISSUE TITLE
Cyber Viking doesn't show the filled xp bar

### ISSUE THREAD

**Issue by viracocha48** [klesun/bcu-bugs-public#17]
![image](https://user-images.githubusercontent.com/89263929/140241540-e1102078-e4c9-44c0-858d-044fd3e82115.png)

As seen above, you can't see the xp bar filling up.

**Comment by klesun** [comment]
Thanks for the report. Funny, our QA brought up this same issue just few hour ago =D

**Comment by klesun** [comment]
Internal ticket: BC-3028
Status: Open

**Comment by klesun** [comment]
Should be fixed now
