### ISSUE TITLE
Able to create an item auction at 0 EOS

### ISSUE THREAD

**Issue by viracocha48** [klesun/bcu-bugs-public#18]
![image](https://user-images.githubusercontent.com/89263929/140394415-74843c54-37b3-48bc-a501-7af5ba497a08.png)

This is impossible to buy as price must be greater than 0

![image](https://user-images.githubusercontent.com/89263929/140394544-27c51d3e-454b-4374-93bf-ac613dee9f62.png)

Not sure if there's much of a need to fix this as the new market system should be replacing the current one, but that restriction should still be there.

**Comment by klesun** [comment]
Internal ticket: BC-3002
Status: Open

**Comment by klesun** [comment]
Solved by the migration to Offchain Market.
