### ISSUE TITLE
Checksum doesn't match on EOS pot drinking

### ISSUE THREAD

**Issue by klesun** [klesun/bcu-bugs-public#2]
Let's gather here all the info we have to help devs reproduce and fix the "checksum doesn't match" error that happens in eos on drinking red pots by certain locked cuties.

![image](https://user-images.githubusercontent.com/5202330/136080669-738cc55c-1cf5-4271-9f35-384050bb40b8.png)

The first report by `Jim Chopper, [09.07.21 19:07]`:
> I have been breeding around 30 cuties 20-25 cuties today and this happened to one of my gen 0 EOS cuties.
> had to switch it out, but now it happened to another one.
> I dont have that many EOS gen 0 cuties...
> Im guessing they are stuck now for a long time?

**Comment by klesun** [comment]
Next report by `Xander Xio ㉫ MvB © Official Enjin Envoy, [09.07.21 20:22]`:
> I get the checksum doesn’t match all the time, usually when I have tried to use a red pot tried other types that sometimes works but in most cases it’s just a waiting game until the grayed out red pot has gone.

**Comment by klesun** [comment]
Next report by `MoonMama, [19.07.21 07:22]`:
> On occasion I get the checksum message which is a pain and if I have no other size potions just wait it out.

**Comment by klesun** [comment]
Next report by `Ricki Martiano, [31.08.21 13:20]`
> Good damn cutie just get born and he got checksum wrong xD

**Comment by klesun** [comment]
Next report by `Maxwell MacIver, [31.08.21 22:39]`
`[In reply to Tehn | Blockchain cuties]`
> Checksum happens all the time

**Comment by klesun** [comment]
Next report by `Pedro Marques, [15.09.21 15:11]`
> Getting a Checksum doesn't match error when tried to use elixir of life on a cutie. Adventure potion works fine on it, elixir of life works fine on other one. Anyone see that before?

**Comment by klesun** [comment]
The issue is known to happen on Wombat Desktop.

**Comment by klesun** [comment]
`Shino Tenshi, [06.10.21 00:21]`
> I've definitely seen it using private key, pretty sure I've seen it using Wombat mobile too

**Comment by viracocha48** [comment]
Just had it happen to me on PC. I have those transactions whitelisted, so usually once I hit the use item button, it will spin a bit until the wombat plugin whitelists the transaction and then it goes through, and moves on to the activity list.

This time I had switched tabs and when I went back the use item screen was still there. Checking on the activity it wasn't showing as pending. Trying to use another potion showed the potion with the Exclamation mark (usually shown when you have already used a potion and waiting for blockchain). And trying to use another one gave me Checksum error.

**Comment by klesun** [comment]
Thanks to MoonMama, we now have the stack trace:
```
eosjs-numeric.js:295 Uncaught (in promise) Error: checksum doesn't match
    at k (eosjs-numeric.js:295)
    at Object.D [as stringToSignature] (eosjs-numeric.js:398)
    at e.pushSignature (eosjs-serialize.js:425)
    at Object.serialize (eosjs-serialize.js:874)
    at Object.k [as serialize] (eosjs-serialize.js:564)
    at H (eosjs-serialize.js:1041)
    at Object.Y [as serializeAction] (eosjs-serialize.js:1051)
    at e.<anonymous> (eosjs-api.js:278)
    at u (eosjs-api.js:47)
    at Object.next (eosjs-api.js:28)
```

**Comment by klesun** [comment]
A screenshot for reference:
![image](https://user-images.githubusercontent.com/5202330/139555866-edcf56be-692d-4ec0-aa11-83bbdb3b4c38.png)

**Comment by klesun** [comment]
This was supposedly fixed
