### ISSUE TITLE
Daywalker's body kit breaks preview

### ISSUE THREAD

**Issue by Capronicus** [klesun/bcu-bugs-public#3]
Seems to only be the body kit
![Screenshot 2021-10-06 160040](https://user-images.githubusercontent.com/39051437/136217862-ddc0b0d7-87f7-404b-8888-350cc300bd63.png)

**Comment by klesun** [comment]
Internal ticket number: BC-2388, status: Open

**Comment by QAteamMember** [comment]
@Capronicus Thank you for the report. The issue should be resolved now. Please inform us if this is still repeating for you!

**Comment by klesun** [comment]
yipee!
![image](https://user-images.githubusercontent.com/5202330/152241696-4a7f92dc-69a0-4414-b003-8a130e0fae24.png)
https://blockchaincuties.com/player/22329557?kind=Fox&level%5Bmin%5D=10&level%5Bmax%5D=12&page=1&sortBy=Age&orderBy=Asc
