### ISSUE TITLE
Rapidly applying season adventure potions produces an error

### ISSUE THREAD

**Issue by Capronicus** [klesun/bcu-bugs-public#5]
When clicking rapidly it produces the following error:

![Screenshot 2021-10-06 155931](https://user-images.githubusercontent.com/39051437/136219471-ff63312b-d0d7-41d4-89d8-f96ee6fc3ce0.png)

no other discernable effect

**Comment by klesun** [comment]
Internal ticket: BC-3240
Fix was released in `22.1.5`

Now you'll see such error ^_^
![image](https://user-images.githubusercontent.com/5202330/151448745-1faf4cd5-478a-4994-9b56-0f1ff0170510.png)
