### ISSUE TITLE
Visual bugs with gear

### ISSUE THREAD

**Issue by Capronicus** [klesun/bcu-bugs-public#7]
Maybe just one ticket for all the visual bugs with sets and gear?

Viking axe + King set aren't layered correctly
![image](https://user-images.githubusercontent.com/39051437/136220760-83239845-ab5a-469f-9282-d00c5fe5e958.png)
(fixed in BC-2992 (c) @klesun)

Gang scrap gear doesn't hide lizard toes
![image](https://user-images.githubusercontent.com/39051437/136221107-212851bf-fb3a-4889-b39c-12757ff5ae7e.png)
(fixed in BC-2992 (c) @klesun)

Warboss Claw doesn't hide cutie arm (lizard, bear, dogs)
![image](https://user-images.githubusercontent.com/39051437/136221482-46934de9-f36f-453b-8cd2-e96d7b5e5c37.png)
seems somewhat correct for pigs, hedgehogs, cats, foxes and bunnies, although some part still stick out
![image](https://user-images.githubusercontent.com/39051437/136221753-3610d4f1-a73d-43c3-8a6e-73ebd94769bc.png)
(fixed in BC-2992 (c) @klesun)

**Comment by klesun** [comment]
Overseer Uniform (Personal) also does not hide Lizzard legs

![image](https://user-images.githubusercontent.com/5202330/136232326-6bd0a35d-84f9-455b-b98d-f30930e0d279.png)
Fixed in BC-2992

**Comment by klesun** [comment]
A ticket for re-structuring the configuration of item display rules: BC-2925. I'm currently working on it, plan to move to Code Review stage today-tomorrow.

Should make it easier to fix such problems and spot mistakes.

**Comment by klesun** [comment]
More broken gear on bear:
![image](https://user-images.githubusercontent.com/5202330/136719047-8582e560-356d-4369-8ec4-e0ed058511a6.png)

**Comment by klesun** [comment]
So hard to be a bear in Cutieland...

![image](https://user-images.githubusercontent.com/5202330/137389383-4af26110-2d05-4d4c-8500-0ee459553cc5.png)
(Fixed in BC-2992)

![image](https://user-images.githubusercontent.com/5202330/137389407-3873bb4c-af0e-44dd-be56-e6cb70891cdf.png)
(Fixed in BC-2992)

![image](https://user-images.githubusercontent.com/5202330/137390725-59c6cb00-2e6d-4ad0-908e-cc72ebedd4fe.png)
(Fixed in BC-2992)

Claws behind the coat:
![image](https://user-images.githubusercontent.com/5202330/137392524-f17acc6b-8faa-4a0c-85fe-83c47e0356ae.png)
(Fixed in BC-2992)

**Comment by klesun** [comment]
The BC-2925 is on Testing Stage now, planned to be released on Tuesday.

Once it's released, fixing most of this stuff will become a piece of cake.

**Comment by Capronicus** [comment]
awesome, I'll see if I can spot some more,I recall I had a couple more but don't know which specifically anymore xD

**Comment by klesun** [comment]
Our QA found so many of them over the weekend that I stopped forwarding them here at some point. I intent to file a patch after BC-2925 is deployed to fix a batch of the issues in my loooong list.

**Comment by klesun** [comment]
Internal ticket with fixes: BC-2992
Status: Code Review

**Comment by klesun** [comment]
The fixes for all mentioned cases were released today. Once you update your cutie (by equipping some item for example) the image should get updated and issue be gone.
