### ISSUE TITLE
Parents/Child image does not show season gear

### ISSUE THREAD

**Issue by viracocha48** [klesun/bcu-bugs-public#8]
Season gear does not show in the image of a parent/child. Images below are of the same cutie.

![image](https://user-images.githubusercontent.com/89263929/136243184-1af1ff14-6b24-4ee4-9e52-f5c22be5fc9d.png)
![image](https://user-images.githubusercontent.com/89263929/136243278-f42d569d-b1b1-4adc-a265-7c846f78818a.png)

**Comment by klesun** [comment]
Thanks for noticing!
Seems like it's not showing those items in parent/child because they are personal. We had a similar issue on several screen.

**Comment by klesun** [comment]
Filed in internal bug tracker: BC-2942

**Comment by klesun** [comment]
Submitted a fix to Code Review

**Comment by klesun** [comment]
The fix is planned to be released on Tuesday at 11:00 GMT+0

**Comment by klesun** [comment]
The fix is in effect now
![image](https://user-images.githubusercontent.com/5202330/137899840-88e36058-74d9-4512-8df6-a8bad7b7a4fa.png)
